name: Publish to PyPI

on:
  release:
    types: [published]
  # workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  pypi-publish:
    name: Build and upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install build tools
      run: python3 -m pip install build

    - name: Build sdist and wheel
      run: python3 -m build
    
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # with:
      #   # Keep token-based publishing support for repositories not yet configured
      #   # for trusted publishing. If trusted publishing is configured in PyPI,
      #   # this can be removed.
      #   password: ${{ secrets.PYPI_API_TOKEN }}