# https://pytest-with-eric.com/integrations/pytest-github-actions/
# https://github.com/mamba-org/setup-micromamba

name: Run unit tests

on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: unit-test-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up mamba environment and dependencies
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          environment-file: environment.yml
          create-args: pytest pytest-cov
          init-shell: bash powershell
          cache-environment: true
          post-cleanup: all
        
      - name: Install strain_tools
        shell: micromamba-shell {0}
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools 
          cd $GITHUB_WORKSPACE
          pip install .

      - name: Test with pytest
        shell: micromamba-shell {0}
        run: |
            coverage run -m pytest -v -s --maxfail=1
            coverage xml
        
      - name: Generate pytest coverage report
        shell: micromamba-shell {0}
        run: |
            coverage report -m